version: "3"
services: 
  my_php:
    container_name: fpm
    build:
      dockerfile: ./kontener/Dockerfile  
    volumes: 
      - ./strona:/app
    networks:
      - static-network
  my_nginx:
    container_name: praktyka
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes: 
      - ./strona:/app
    
networks:
  static-network:


