version: "3"
services: 
  fpm:
    container_name: fpm
    build:
      dockerfile: ./kontener/Dockerfile  
    volumes: 
      - ./strona:/app
    networks:
      - static-network
  my_nginx:
    container_name: praktyka
    build:
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - fpm
    ports:
      - 80:80
    volumes: 
      - ./strona:/app
      - ./nginx/konf.conf:/etc/nginx/conf.d/default.conf
    networks:
      - static-network
    
networks:
  static-network:


