version: "3"
services: 
  my_php:
    container_name: fpm
    build:
      dockerfile: ./kontener/Dockerfile  
    volumes: 
      - ./kontener/index.php:/app/index.php
    networks:
      - static-network
  my_nginx:
    container_name: praktyka
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes: 
      - ./nginx/index.php:/app/index.php
    
networks:
  static-network:
  
