FROM php:8.3-fpm-bookworm


RUN apt-get update && apt-get install -y \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install gd


RUN apt install libzip-dev
	docker-php-ext-install zip
	


